### ISSUE TITLE
Macro erases itself

### ISSUE THREAD

**Issue by viruzx** [MaxPleaner/linux-keyboard-macros#2]
When I type "hello world" it is suppose to ouput "hello_world". However, what it does is it just erases the "hello world" part.

Any ideas?

**Comment by viruzx** [comment]
Whoops.. I read the source and it seems I didn't understand how the source worked. I do now though. Closing!

**Comment by MaxPleaner** [comment]
😄 I'm flattered you tried it out. Glad to hear it worked
