### ISSUE TITLE
Errno:EIO error

### ISSUE THREAD

**Issue by rxsh** [MaxPleaner/linux-keyboard-macros#4]
I'm having this problem when trying to open the app, I did bundle install and installed all the dependencies:

Errno:EIO error, but this probably just means that the process has finished giving output.

It isn't an issue with the code itself but I don't know where to ask how to fix this

**Comment by MaxPleaner** [comment]
There are two things you might need to configure when using this app. I just used this myself yesterday for the time in a while and I had to figure out this same error I might add:

1. try enter superuser with `sudo su` then `bundle` and `./macros_server.rb`
2. edit line 228 to be the correct device number (for example mine is `echo '6'`). you can figure this out by doing `sudo evtest`, picking a number corresponding to a keyboard, and verifying that it prints output when you type characters. 

To to honest the superuser-related code here is kind of messy (and the rest of the code isn't the cleanest either) , might refactor it at some point in the future.

**Comment by MaxPleaner** [comment]
also if you want you can clone the "personal" branch instead, it has some improvements I added yesterday such as separate files for keymap and macro definitions

**Comment by rxsh** [comment]
Now it works, thanks buddy! I will have a look to the personal branch so.
